# This is a basic workflow to help you get started with Actions

name: DL_files

# Controls when the workflow will run
on:
  schedule:
    # Minute(0-60), hour(0-23), day(1-31), month(1-12), day(Mon-Sun)
    # Every days, at minute 16 from 6am to 6pm 
    - cron:  '16 6-18 * * *' 


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show CWD
        run : |
          pwd
          ls
      - name: Install dependencies
        run: pip install pandas wget
      - name: Run code to DL files
        run: python src/merge_measurements.py

      - name: Commit DB
        run: |
          git config --global user.name 'Marc Automated Action'
          git config --global user.email 'Marc@users.noreply.github.com'
          git add db/*
          git commit -m "Automated DB update"
          git push
